language: python

python:
  - '2.7'

install:
  - 'pip install -r requirements.txt --use-mirrors'

before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
  - unzip -q google_appengine_1.8.9.zip
  - export PYTHONPATH=$PYTHONPATH:./google_appengine

script: './run_tests.sh'
