application: cs-muninn
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /agents/.*
  script: muninn.handlers.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: django
  version: "latest"
- name: lxml
  version: "2.3"
- name: ssl
  version: "2.7"
- name: pycrypto
  version: "latest"
- name: jinja2
  version: latest

builtins:
- remote_api: on
- deferred: on
- appstats: on