application: cs-muninn
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /assets/
  static_dir: assets

includes:
- muninn/include.yaml

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: lxml
  version: latest


builtins:
- remote_api: on
- deferred: on
- appstats: on